import type { Metadata } from 'next'
import { ClerkProvider } from '@clerk/nextjs'
import { neobrutalism } from '@clerk/themes'
import { ptBR } from '@clerk/localizations'
import { Toaster } from 'sonner'

import { Geist, Geist_Mono } from 'next/font/google'
import { Navbar } from '@/components/navbar'
import { AuthCheck } from '@/components/auth-check'
import './globals.css'

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
})

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
})

export const metadata: Metadata = {
  title: 'Study Planner',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <ClerkProvider
      localization={ptBR}
      appearance={{
        baseTheme: neobrutalism,
      }}
    >
      <html lang="pt-BR">
        <body
          className={`${geistSans.variable} ${geistMono.variable} antialiased`}
        >
          <AuthCheck />
          <nav className="sticky top-0 z-50 w-full bg-background/95 backdrop-blur supports-[backdrop-filter]:bg-background/60">
            <Navbar />
          </nav>
          <main className="flex min-h-screen flex-col items-center p-4">
            {children}
          </main>
          <Toaster richColors position="top-right" />
        </body>
      </html>
    </ClerkProvider>
  )
}
